services:
    resource-server:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_NAME=resource-service
        image: 192.168.10.64:4999/resource/resource-server:${TAG:-latest}
        command: npm run start -- resource-service
        ports:
            - '5001:5001'
        environment:
            NODE_ENV: production
            TZ: Asia/Seoul
            APP_NAME: resource-service
            APP_PORT: 5001
            # POSTGRES_HOST: attendance-postgres
            # POSTGRES_PORT: 5432
            # POSTGRES_DB: resource-server
            # POSTGRES_USER: admin
            # POSTGRES_PASSWORD: tech7admin!

            POSTGRES_PORT: 6543
            POSTGRES_HOST: aws-0-ap-northeast-2.pooler.supabase.com
            POSTGRES_USER: postgres.pvwepnpkabixsiglxvff
            POSTGRES_PASSWORD: zIDDlwP2vOQFYU4W
            POSTGRES_DB: postgres

            JWT_SECRET: 13hjkabsud23l13asbizx
            JWT_EXPIRES_IN: 24h
            GMAIL_USER: noti.lumir.space@gmail.com
            GMAIL_APP_PASSWORD: zlwmvrkqhhmrjmno
            REDIS_HOST: attendance-redis
            REDIS_PORT: 6379
            NATS_URL: nats://nats:4222
            WEB_PUSH_PUBLIC_KEY: BIjDkj2RVRCmukBgreTh-TeXZpZ7EhR10nLXr6lumCndXkM9D8QvCnGvvR2U0ZcYNEEhlUxdD_srRB9jY2Nlp04
            WEB_PUSH_PRIVATE_KEY: K3IKvIlZuci9qjpfGufuGIvkgsFV0ivW9rR-FPZ-QHA

            S3_ACCESS_KEY: 06016141fb7a60933f2c3446c8554e0b
            S3_SECRET_KEY: ab764d8bdd8219b3d663c7016f30e718b5f7d8ad4dbbfa6b679e9d49e62b7552
            S3_BUCKET_NAME: rms
            S3_REGION: ap-northeast-2
            S3_ENDPOINT: https://sdjojmvjvzszrdekyrnv.supabase.co/storage/v1/s3

            FIREBASE_TYPE: service_account
            FIREBASE_PROJECT_ID: lumir-notification
            FIREBASE_PRIVATE_KEY_ID: 03e14d119038987e0180bbb1d001db6f2999fbf9
            FIREBASE_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSCxcNXwXgRbXr\nXZu3loi4QR0rBkrdRGnu5/OkJXIrFCF0WiE/1XevGJlbtr2iHxwxGYmnmMpD+Dph\nsVcYktVqhoiGEvZTkiAp+0cqPpcdq7xdQWbotqUhSQOuPPYQhT5mvGgmBZRkFWnC\nHGvnRzYpOXEwKxoTmdPjZ+Q1i7Y48QXC6oXRpQV0nWDA7yASfkSbIdSoGTqCLk5S\nUSBCBiX8Q2/l0T5r4SuJYRqDiKDBo1wisY/cYs+zaPWjFidLl0I5jIMGJKEYlmI7\nPjc9DnDh3xUk4yJJ5lfL+vtFMhZ0D7SMOoj30/U2ylny82V8XA45IKhELEcEvR7r\nVOd3TDFXAgMBAAECggEAC8u8pS8XdONlVo0AwDwvfG2HtlFZpfiAHH8hQzApK7sr\nL84Z/Ow/lvFCN5DZMIAfxLAi92sQvOV1XeQoOISSgLOCekkZVVMpBEKM2hX+xZdN\n8kzIezw6pNZlYwUgaogZG4rsLGp2zXIYaOLQuoHYzFLiBOr+wWgLqsM8YTdx6duh\nOZrwwIojk1uC2qFZVxMtCBEtgVST4kKUDj4p6C4CTo7ijvE0kUuFxaxhfhlL/lXe\n25BKMmjN1WoVCLmLxmF54QEd5bmOUDLiQhttjUeNUwctip06IAZpK6x/QSKEsDf7\nZl/NevYkuCqwVDn70nFeO1kM1ebor9oJmjmSlv3Q6QKBgQD1P/sZhHXebcTQuEKQ\nP6iJhdKQUhMgTPxgcew/BxknEgxHOb/sXpYh+Z6d1S+HZ1RNXHswZyC/AeaspwYk\nJ1iOg3Cxlrq6Jerl7dHzqZuzdOss0kxMc3T8G0hS+KHSqiKcxeW9SxXRs/fmeO/i\nnad7+KCCaieFwhoftPX2EBPmLwKBgQDbQAu9/wLWYIg2BNWaDbZ1RGJjxlDcI/uM\npmdxZTi1SROA4YC/iF2ji133qDT+QGikC6dQNiLaQDVcKSENrzMsJgYxbuUv5Os8\nhTp8WpRCM7VNb7biRUcFFmByjt2xUpdkVLKi7nbdwoG7Xk8Lnycm+2CXcIUu92WD\nR9EzgvHFWQKBgQDIXNsiP8ukSv2un7sR6lAg+onKiqNBkmPlz2z5GS19dAs/7XhU\n/fmeDDeALvlDoDGJenLSWo6wPjdc+p/TzalV1SCulbw79FpyOtd6QCkKdgzkc3MO\nSo1aold2IdbjK0hX2H4XJk7PIj73tfoVpEN+zuMjaOKdLrT1Dnyb6Qq41QKBgDPi\nayTyNSSwQWuvJzFGr3f+z93Wr4n5Be1Z777Y+luESJZGRyaMScSLFZim+Kt2aIzx\nqQ2FUigd68K8hPLtFAoNkYefO6Ni4/w1dwq4kL8951jE6B2R0WW1zustPe9ZoTQA\nCyodjomaHwNNJR2V8zj5YflUil/78czocOxkv3w5AoGAahTHhUIHkSiEyQcAy95Y\nfXND6wwCF8ffEZCRzcsCE89U/SodM1Sj5H8g7nnBRZeiwNDelw9Mb8AO6JkeWM1X\nlcw0hF1u9nJ787J6aAGTYCcuuLru1cfxmCtWCB2qV/x/ajsHCwGvLh/pfThyNp2A\nbXohSR5KnEnJpdROLAmvbLs=\n-----END PRIVATE KEY-----\n
            FIREBASE_CLIENT_EMAIL: firebase-adminsdk-fbsvc@lumir-notification.iam.gserviceaccount.com
            FIREBASE_CLIENT_ID: 102007938759114614541
            FIREBASE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
            FIREBASE_TOKEN_URI: https://oauth2.googleapis.com/token
            FIREBASE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
        # depends_on:

        # - nats
        networks:
            - backend-attendance-management_app_network
            - resource-network

volumes:
    redis_data:
    postgres_data:
    files:

networks:
    backend-attendance-management_app_network:
        external: true
    resource-network:
        driver: bridge
