services:
    resource-server:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_NAME=resource-service
        image: 192.168.10.64:4999/resource/resource-server:${TAG:-latest}
        command: npm run start -- resource-service
        ports:
            - '5001:5001'
        environment:
            NODE_ENV: production
            TZ: Asia/Seoul
            APP_NAME: resource-service
            APP_PORT: 5001
            POSTGRES_HOST: attendance-postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: resource-server
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: tech7admin!
            JWT_SECRET: 13hjkabsud23l13asbizx
            JWT_EXPIRES_IN: 24h
            GMAIL_USER: noti.lumir.space@gmail.com
            GMAIL_APP_PASSWORD: zlwmvrkqhhmrjmno
            REDIS_HOST: attendance-redis
            REDIS_PORT: 6379
            NATS_URL: nats://nats:4222
            WEB_PUSH_PUBLIC_KEY: BH87CE8fWmQUBVd9G8MrVDxifUV9nqz4iN5gssoSdZijAAwLiJuWpqktclMrWFIAaxlJ5wdw3ayGhx2dbS4y5BI
            WEB_PUSH_PRIVATE_KEY: 1Oitw9QsHXJG7gFiFlaXc3n98Q2KVDNo7Jn-Kj7WU4U
        # depends_on:

        # - nats
        networks:
            - backend-attendance-management_app_network
            - resource-network

volumes:
    redis_data:
    postgres_data:
    files:

networks:
    backend-attendance-management_app_network:
        external: true
    resource-network:
        driver: bridge
