import { ResourceType } from '@libs/enums/resource-type.enum';
import { Role } from '@libs/enums/role-type.enum';

export const employeesSeedData = [
    {
        name: '관리자',
        employeeNumber: '00000',
        position: '관리자',
        department: '관리자',
        email: 'admin@lumir.space',
        password: '1234',
        roles: [Role.USER, Role.RESOURCE_ADMIN, Role.SYSTEM_ADMIN],
    },
    {
        name: '김종식',
        employeeNumber: '23027',
        position: '선임연구원',
        department: 'Web파트',
        email: 'kim.jongsik@lumir.space',
        password: '1234',
    },
    {
        name: '우창욱',
        employeeNumber: '23047',
        position: '연구원',
        department: 'Web파트',
        email: 'woo.changuk@lumir.space',
        password: '1234',
    },
    {
        name: '김민수',
        employeeNumber: '24008',
        position: '연구원',
        department: 'Web파트',
        email: 'kim.minsu@lumir.space',
        password: '1234',
    },
    {
        name: '김규현',
        employeeNumber: '24016',
        position: '연구원',
        department: 'Web파트',
        email: 'kim.kyuhyun@lumir.space',
        password: '1234',
    },
    {
        name: '김성훈',
        employeeNumber: '24017',
        position: '연구원',
        department: 'Web파트',
        email: 'kim.seonghun@lumir.space',
        password: '1234',
    },
    {
        name: '조민경',
        employeeNumber: '24019',
        position: '연구원',
        department: 'Web파트',
        email: 'jo.minkyeong@lumir.space',
        password: '1234',
    },
    {
        name: '이화영',
        employeeNumber: '24024',
        position: '연구원',
        department: 'Web파트',
        email: 'lee.hwayoung@lumir.space',
        password: '1234',
    },
    {
        name: '황성빈',
        employeeNumber: '24048',
        position: '연구원',
        department: 'Web파트',
        email: 'hwang.sungbin@lumir.space',
        password: '1234',
    },
    {
        name: '전영미',
        employeeNumber: '20029',
        position: '이사',
        department: '경영지원실',
        email: 'jeon.youngmi@lumir.space',
        password: '1234',
    },
    {
        name: '박태연',
        employeeNumber: '22008',
        position: '책임매니저',
        department: '경영지원실',
        email: 'park.taeyeon@lumir.space',
        password: '1234',
    },
    {
        name: '정재일',
        employeeNumber: '23012',
        position: '책임매니저',
        department: '경영지원실',
        email: 'jung.jaeil@lumir.space',
        password: '1234',
    },
    {
        name: '박승현',
        employeeNumber: '24044',
        position: '책임매니저',
        department: '경영지원실',
        email: 'park.david@lumir.space',
        password: '1234',
    },
    {
        name: '우은진',
        employeeNumber: '22020',
        position: '선임매니저',
        department: '경영지원실',
        email: 'woo.eunjin@lumir.space',
        password: '1234',
    },
    {
        name: '이서연',
        employeeNumber: '22042',
        position: '선임매니저',
        department: '경영지원실',
        email: 'lee.seoyeon@lumir.space',
        password: '1234',
    },
    {
        name: '김민영',
        employeeNumber: '23006',
        position: '선임매니저',
        department: '경영지원실',
        email: 'kim.minyoung@lumir.space',
        password: '1234',
    },
    {
        name: '김민찬',
        employeeNumber: '23032',
        position: '매니저',
        department: '경영지원실',
        email: 'kim.minchan@lumir.space',
        password: '1234',
    },
    {
        name: '조아라',
        employeeNumber: '24047',
        position: '매니저',
        department: '경영지원실',
        email: 'cho.ahra@lumir.space',
        password: '1234',
    },
    {
        name: '강남규',
        employeeNumber: '17007',
        position: '책임연구원',
        department: '전자1파트',
        email: 'kang.nk@lumir.space',
        password: '1234',
    },
    {
        name: '정석화',
        employeeNumber: '22025',
        position: '책임연구원',
        department: '전자1파트',
        email: 'jung.suckhwa@lumir.space',
        password: '1234',
    },
    {
        name: '정양희',
        employeeNumber: '20035',
        position: '책임연구원',
        department: '전자1파트',
        email: 'jeong.yanghee@lumir.space',
        password: '1234',
    },
    {
        name: '정성훈',
        employeeNumber: '21008',
        position: '책임연구원',
        department: '전자1파트',
        email: 'jeong.sunghoon@lumir.space',
        password: '1234',
    },
    {
        name: '이준',
        employeeNumber: '21013',
        position: '책임연구원',
        department: '전자1파트',
        email: 'lee.jun@lumir.space',
        password: '1234',
    },
    {
        name: '조수형',
        employeeNumber: '19003',
        position: '책임연구원',
        department: '전자1파트',
        email: 'cho.sh@lumir.space',
        password: '1234',
    },
    {
        name: '정영식',
        employeeNumber: '24041',
        position: '책임연구원',
        department: '전자1파트',
        email: 'jeung.youngsic@lumir.space',
        password: '1234',
    },
    {
        name: '김기표',
        employeeNumber: '23025',
        position: '선임연구원',
        department: '전자1파트',
        email: 'kim.kipyo@lumir.space',
        password: '1234',
    },
    {
        name: '하태식',
        employeeNumber: '23022',
        position: '연구원',
        department: '전자1파트',
        email: 'ha.taesik@lumir.space',
        password: '1234',
    },
    {
        name: '최은지',
        employeeNumber: '23034',
        position: '연구원',
        department: '전자1파트',
        email: 'choi.eunji@lumir.space',
        password: '1234',
    },
    {
        name: '서상준',
        employeeNumber: '22038',
        position: '책임연구원',
        department: '전자2파트',
        email: 'seo.sangjun@lumir.space',
        password: '1234',
    },
    {
        name: '이승기',
        employeeNumber: '23048',
        position: '책임연구원',
        department: '전자2파트',
        email: 'lee.seungky@lumir.space',
        password: '1234',
    },
    {
        name: '전구영',
        employeeNumber: '23010',
        position: '책임연구원',
        department: '전자2파트',
        email: 'jeon.kuyoung@lumir.space',
        password: '1234',
    },
    {
        name: '천윤범',
        employeeNumber: '25004',
        position: '책임연구원',
        department: '전자2파트',
        email: 'chun.yoonbum@lumir.space',
        password: '1234',
    },
    {
        name: '정승헌',
        employeeNumber: '24005',
        position: '연구원',
        department: '전자2파트',
        email: 'jeong.seungheon@lumir.space',
        password: '1234',
    },
    {
        name: '이준형',
        employeeNumber: '24046',
        position: '연구원',
        department: '전자2파트',
        email: 'lee.junhyeong@lumir.space',
        password: '1234',
    },
    {
        name: '김경민',
        employeeNumber: '23028',
        position: '책임연구원',
        department: 'RF파트',
        email: 'kim.kyoungmin@lumir.space',
        password: '1234',
    },
    {
        name: '홍연창',
        employeeNumber: '25006',
        position: '책임연구원',
        department: 'RF파트',
        email: 'hong.yonchang@lumir.space',
        password: '1234',
    },
    {
        name: '유경준',
        employeeNumber: '25007',
        position: '책임연구원',
        department: 'RF파트',
        email: 'yu.gyeongjun@lumir.space',
        password: '1234',
    },
    {
        name: '신승규',
        employeeNumber: '25003',
        position: '책임연구원',
        department: 'RF파트',
        email: 'shin.seunggyu@lumir.space',
        password: '1234',
    },
    {
        name: '박평식1',
        employeeNumber: '24006',
        position: '선임연구원',
        department: 'RF파트',
        email: 'park.pyungsik1@lumir.space',
        password: '1234',
    },
    {
        name: '박영배',
        employeeNumber: '24045',
        position: '선임연구원',
        department: 'RF파트',
        email: 'park.youngbae@lumir.space',
        password: '1234',
    },
    {
        name: '담현규',
        employeeNumber: '25005',
        position: '선임연구원',
        department: 'RF파트',
        email: 'dam.hyounkyou@lumir.space',
        password: '1234',
    },
    {
        name: '김은정',
        employeeNumber: '23036',
        position: '연구원',
        department: 'RF파트',
        email: 'kim.eunjeong@lumir.space',
        password: '1234',
    },
    {
        name: '박창서',
        employeeNumber: '19002',
        position: '책임연구원',
        department: '안테나파트',
        email: 'park.cs@lumir.space',
        password: '1234',
    },
    {
        name: '김익환',
        employeeNumber: '24038',
        position: '선임연구원',
        department: '안테나파트',
        email: 'kim.ikhwan@lumir.space',
        password: '1234',
    },
    {
        name: '고영훈',
        employeeNumber: '22002',
        position: '책임연구원',
        department: '기구파트',
        email: 'ko.younghun@lumir.space',
        password: '1234',
    },
    {
        name: '박동조',
        employeeNumber: '23045',
        position: '선임연구원',
        department: '기구파트',
        email: 'park.dongjo@lumir.space',
        password: '1234',
    },
    {
        name: '구석현',
        employeeNumber: '24020',
        position: '선임연구원',
        department: '기구파트',
        email: 'koo.sukhyun@lumir.space',
        password: '1234',
    },
    {
        name: '손진우',
        employeeNumber: '22040',
        position: '선임연구원',
        department: '기구파트',
        email: 'son.jinwoo@lumir.space',
        password: '1234',
    },
    {
        name: '김동현1',
        employeeNumber: '23035',
        position: '연구원',
        department: '기구파트',
        email: 'kim.donghyun1@lumir.space',
        password: '1234',
    },
    {
        name: '박일수',
        employeeNumber: '24031',
        position: '책임연구원',
        department: '지상운용파트',
        email: 'park.ilsoo@lumir.space',
        password: '1234',
    },
    {
        name: '김형기',
        employeeNumber: '22011',
        position: '연구원',
        department: '지상운용파트',
        email: 'kim.hyunggi@lumir.space',
        password: '1234',
    },
    {
        name: '박정조',
        employeeNumber: '22014',
        position: '연구원',
        department: '지상운용파트',
        email: 'park.jeongjo@lumir.space',
        password: '1234',
    },
    {
        name: '김일진',
        employeeNumber: '22035',
        position: '책임연구원',
        department: 'SAR시스템파트',
        email: 'kim.iljin@lumir.space',
        password: '1234',
    },
    {
        name: '이해림',
        employeeNumber: '24003',
        position: '연구원',
        department: 'SAR시스템파트',
        email: 'lee.haerim@lumir.space',
        password: '1234',
    },
    {
        name: '민정호',
        employeeNumber: '24026',
        position: '연구원',
        department: '영상분석파트',
        email: 'min.jeongho@lumir.space',
        password: '1234',
    },
    {
        name: '손성빈',
        employeeNumber: '24032',
        position: '연구원',
        department: '영상분석파트',
        email: 'son.sungbin@lumir.space',
        password: '1234',
    },
    {
        name: '김형진',
        employeeNumber: '24043',
        position: '책임연구원',
        department: '추진파트',
        email: 'kim.hyungjin@lumir.space',
        password: '1234',
    },
    {
        name: '김기용',
        employeeNumber: '24004',
        position: '책임제조원',
        department: '제조파트',
        email: 'kim.kiyong@lumir.space',
        password: '1234',
    },
    {
        name: '김동현',
        employeeNumber: '22005',
        position: '선임제조원',
        department: '제조파트',
        email: 'kim.donghyun@lumir.space',
        password: '1234',
    },
    {
        name: '안광헌',
        employeeNumber: '25001',
        position: '선임제조원',
        department: '제조파트',
        email: 'an.gwangheon@lumir.space',
        password: '1234',
    },
    {
        name: '원동주',
        employeeNumber: '24035',
        position: '연구원',
        department: '제조파트',
        email: 'won.dongju@lumir.space',
        password: '1234',
    },
    {
        name: '채민수',
        employeeNumber: '22037',
        position: '제조원',
        department: '제조파트',
        email: 'chae.minsu1@lumir.space',
        password: '1234',
    },
    {
        name: '남명조',
        employeeNumber: '24042',
        position: '제조원',
        department: '제조파트',
        email: 'nam.myungjo@lumir.space',
        password: '1234',
    },
    {
        name: '최동원',
        employeeNumber: '25002',
        position: '제조원',
        department: '제조파트',
        email: 'choi.dongwon@lumir.space',
        password: '1234',
    },
    {
        name: '박재훈',
        employeeNumber: '25008',
        position: '선임연구원',
        department: 'QA파트',
        email: 'park.jaehun@lumir.space',
        password: '1234',
    },
    {
        name: '서유민1',
        employeeNumber: '24010',
        position: '연구원',
        department: 'QA파트',
        email: 'seo.yumin1@lumir.space',
        password: '1234',
    },
    {
        name: '윤성영',
        employeeNumber: '23050',
        position: '연구원',
        department: 'QA파트',
        email: 'youn.sungyoung@lumir.space',
        password: '1234',
    },
    {
        name: '이우림',
        employeeNumber: '20032',
        position: '연구원',
        department: 'QA파트',
        email: 'lee.woolim@lumir.space',
        password: '1234',
    },
    {
        name: '강민기',
        employeeNumber: '24028',
        position: '연구원',
        department: 'PA파트',
        email: 'kang.minki@lumir.space',
        password: '1234',
    },
    {
        name: '김성훈1',
        employeeNumber: '24034',
        position: '연구원',
        department: 'PA파트',
        email: 'kim.seonghun1@lumir.space',
        password: '1234',
    },
];

export const resourceGroupsSeedData = [
    {
        title: '회의실',
        description: '회의 공간',
        type: ResourceType.MEETING_ROOM,
    },
    {
        title: '차량',
        description: '업무용 차량',
        type: ResourceType.VEHICLE,
    },
    {
        title: '숙소',
        description: '숙소',
        type: ResourceType.ACCOMMODATION,
    },
];

export const subResourceGroupsSeedData = [
    {
        title: '11층 회의실',
        description: '11층 회의실',
        type: ResourceType.MEETING_ROOM,
    },
    {
        title: '5층 회의실',
        description: '5층 회의실',
        type: ResourceType.MEETING_ROOM,
    },
    {
        title: '법인 차량',
        description: '법인 차량',
        type: ResourceType.VEHICLE,
    },
    {
        title: '대전 숙소',
        description: '대전 숙소',
        type: ResourceType.ACCOMMODATION,
    },
    {
        title: '사천 숙소',
        description: '사천 숙소',
        type: ResourceType.ACCOMMODATION,
    },
];

export const resourcesSeedData = [
    {
        name: '11층 대회의실',
        description: '11층 대회의실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '11층 중회의실',
        description: '11층 중회의실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '11층 소회의실',
        description: '11층 소회의실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '대표이사실',
        description: '대표이사실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '5층 중회의실',
        description: '5층 중회의실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '5층 소회의실',
        description: '5층 소회의실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '5층 오대수이사실',
        description: '5층 오대수이사실',
        type: ResourceType.MEETING_ROOM,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '럭셔리모텔1',
        description: '럭셔리모텔1',
        type: ResourceType.ACCOMMODATION,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '럭셔리모텔2',
        description: '럭셔리모텔2',
        type: ResourceType.ACCOMMODATION,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '럭셔리모텔3',
        description: '럭셔리모텔3',
        type: ResourceType.ACCOMMODATION,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '럭셔리모텔4',
        description: '럭셔리모텔4',
        type: ResourceType.ACCOMMODATION,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '럭셔리모텔5',
        description: '럭셔리모텔5',
        type: ResourceType.ACCOMMODATION,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '럭셔리모텔6',
        description: '럭셔리모텔6',
        type: ResourceType.ACCOMMODATION,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '싼타페(25어5677)',
        description: '싼타페(25어5677)',
        type: ResourceType.VEHICLE,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '스타렉스(75누7885)',
        description: '스타렉스(75누7885)',
        type: ResourceType.VEHICLE,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '셀토스(126서1152)',
        description: '셀토스(126서1152)',
        type: ResourceType.VEHICLE,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
    {
        name: '카니발(116너5351)',
        description: '카니발(116너5351)',
        type: ResourceType.VEHICLE,
        images: ['https://www.lumir-inc.com/assets/imgs/renewal/introduce/overview/%EC%82%BC%EC%A1%B1%EC%98%A4.png'],
    },
];
