export enum NotificationType {
    RESERVATION_CREATED = 'RESERVATION_CREATED',
    RESERVATION_REJECTED = 'RESERVATION_REJECTED',
    RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
    RESERVATION_REMINDER = 'RESERVATION_REMINDER',
    PARTICIPANT_CHANGED = 'PARTICIPANT_CHANGED',
    CONSUMABLE_CHANGING = 'CONSUMABLE_CHANGING',
}
