export enum NotificationType {
    RESERVATION_STATUS_CONFIRMED = 'RESERVATION_STATUS_CONFIRMED',
    RESERVATION_STATUS_CANCELLED = 'RESERVATION_STATUS_CANCELLED',
    RESERVATION_DATE_UPCOMING = 'RESERVATION_DATE_UPCOMING',
    RESERVATION_PARTICIPANT_CHANGED = 'RESERVATION_PARTICIPANT_CHANGED',
    RESOURCE_CONSUMABLE_REPLACING = 'RESOURCE_CONSUMABLE_REPLACING',
}
